### ISSUE TITLE
（提供建议）希望可以同时导出同个视频的封面

### ISSUE THREAD

**Issue by jng640** [iszhouhua/social-media-copilot#1]
您好！
非常感谢您所制作的社媒助手！

我想提供个建议，希望能增加同时导出视频封面的选项。
抖音上有许多影片分段成几个部分，比如《西游记》可能分成5部解说影片，但这些影片的标题并没有显示哪个先哪个后，通常先后都是显示在封面上，又有一些好几百集的漫画小说，所有的视频标题也没显示数目字。所以如果可以同时导出封面（封面拥有与视频相同的标题），这样就比较好分辨了。

还有就是如果可以添加单纯针对合集的下载，会更好哦！

谢谢您！

**Comment by iszhouhua** [comment]
可以的，很合理。会考虑加上的
