### ISSUE TITLE
chrome商店版和github仓库是否存在代码差异？

### ISSUE THREAD

**Issue by kkkkkkkk566** [iszhouhua/social-media-copilot#11]
使用chrome商店版下载小红书笔记的时候发现有点问题，比如总共有50条笔记，有时会下载个3、4条就结束不再下载了，于是想debug源码看看哪里有问题。
但是下载了github的代码，在main最新commit或者v0.0.7，都发现跟商店版行为不一致：
1.下载的形式不同，商店版会为每篇笔记建一个目录存放，github版不会建目录，所有笔记平摊在同一层级
2.商店版下载的是原图，github版下载的是压缩图
3.商店版下载的素材前不会有【社媒助手】前缀，github版有

**Comment by iszhouhua** [comment]
商店版和开源版并不完全相同
