### ISSUE TITLE
抖音批量抓取的时候，导出的数据会出现顺序错乱也

### ISSUE THREAD

**Issue by schuihui** [iszhouhua/social-media-copilot#2]
数据是对的，但是顺序乱了~~能严格按照输入的顺序吗~~谢谢大佬~~另外，出现错误的链接能直接填错“链接无效”然后继续采集不，不然数量比较多的时候，有时候链接失效，没办法一条一条去检查~~~

**Comment by schuihui** [comment]
我懂了，顺序乱了是因为有的链接视频被删了，导致抓不到数据但是没有空行，就直接顺序乱掉了，抓不到数据的可以填充一下内容，这样顺序就不乱了

**Comment by iszhouhua** [comment]
可以，下一版优化一下
