### ISSUE TITLE
（提供建议）希望能直接压缩ZIP文件

### ISSUE THREAD

**Issue by jng640** [iszhouhua/social-media-copilot#3]
您好，感谢您的更新！

我想问目前的下载都是直接一个一个文件不间断的跳出来下载，是否可以直接把所有需要下载的视频+封面(同一个任务)直接压缩成一个ZIP下载呢？这样就不会一直跳一个个文件下载了。

**Comment by iszhouhua** [comment]
这个没办法实现哦，如果强行实现，浏览器内存会撑不住的。
因为想要压缩成zip之后再下载，需要先下载所有的视频到内存之中，然后才能进行压缩。
如果不想一直提示下载，可以关闭Chrome下载设置中的”下载前询问每个文件的保存位置“，这样就不会一直弹窗了。

**Comment by jng640** [comment]
好的，谢谢！
