### ISSUE TITLE
导出笔记，这个功能里的笔记链接不可用，会提示访问链接异常。能否使用底层页里分享链接？

### ISSUE THREAD

**Issue by ppprice** [iszhouhua/social-media-copilot#9]

**Comment by iszhouhua** [comment]
可以用app的分享链接或完整的笔记链接

**Comment by ppprice** [comment]
这个链接希望能直接写入excel

**Comment by iszhouhua** [comment]
excel里不是有链接吗？

**Comment by ppprice** [comment]
这个链接不可用啊。
![image](https://github.com/user-attachments/assets/7e6d99c3-17d1-4766-a027-377634650a6e)

**Comment by iszhouhua** [comment]
怎么不能用了，你复制到浏览器打开不就行了。小红书的笔记链接就是这个

**Comment by iszhouhua** [comment]
如果用不了的话，我也没办法。因为现在能拿到的就只有这个链接。如果你有办法获取有效链接，欢迎提PR
